version: "3.5"

services:

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - server
    networks:
      - backend-net
    ports:
      - "8080:8080"

  server:
    container_name: server
    image: postgrest/postgrest
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ${DB_USER} 
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - database
    networks:
      - backend-net
    ports:
      - "3000:3000"

  database:
    container_name: database
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data
    volumes:
      - database-vol:/data
    networks:
      - backend-net
    ports:
      - "5432:5432"

networks:
  backend-net:

volumes:
  database-vol:

