"""add_creation_date

Revision ID: 7df7e1bc9fa4
Revises: 85906ed254cd
Create Date: 2021-10-27 07:53:11.664942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df7e1bc9fa4'
down_revision = '85906ed254cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('creation_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'creation_date')
    # ### end Alembic commands ###
